name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PICO-8
        run: |
          wget https://raw.githubusercontent.com/robert5800/pico-8-autoinstall/main/install
          chmod +x install
          ./install
      - name: Run PICO-8
        run: pico8 -export export/game.html p8sweeper.p8
